-- Datos de prueba, después de schema.sql. Usuarios y claves en el README.

INSERT INTO usuarios (id, nombre, usuario, clave, rol) VALUES
    (1, 'Administrador', 'admin', '$argon2id$v=19$m=65536,t=4,p=1$QmNMQXRHMkduenhXdmY5Lw$UYbZvbEjII90V3ZvyIJ2G2MBDb73EkeMiLvtTQQZpWU', 1),
    (2, 'Gloria', 'gloria', '$argon2id$v=19$m=65536,t=4,p=1$UWtlRVhPTU0uL1dtVFBMeg$yDi0W7fj0U7wOxKDuHt4XrPuHtDLecTjastnlkufpOY', 0),
    (3, 'Pan', 'pan', '$argon2id$v=19$m=65536,t=4,p=1$RFk1SnJOQ0czNXJtUGp4dg$29iQIAs7lw03/d1mb+NQLIAXbsuo+mglME9r94ynecc', 0);

-- El primero es este sistema; sus requerimientos salen del IR.
INSERT INTO proyectos (id, nombre, descripcion) VALUES
    (1, 'Formulación de pruebas', 'Este sistema: casos de prueba, formularios y evidencias.'),
    (2, 'Biblioteca escolar', 'Préstamo y devolución de libros para estudiantes.');

-- Gloria en los dos; Pan solo en el primero.
INSERT INTO proyecto_miembros (proyecto_id, usuario_id) VALUES
    (1, 2), (1, 3), (2, 2);

INSERT INTO requerimientos (id, proyecto_id, codigo, descripcion, no_funcional) VALUES
    (1, 1, 'RF-01', 'Iniciar sesión con usuario y contraseña. Un inicio fallido no dice si el usuario existe.', 0),
    (2, 1, 'RNF-03', 'Evidencias: solo png, jpg, txt o log, o un enlace. Máximo 5 MB. El archivo se renombra y se guarda fuera de la raíz pública.', 1),
    (3, 2, 'RF-01', 'Prestar un libro. No se presta si el estudiante tiene 3 préstamos activos o una multa sin pagar.', 0),
    (4, 1, 'RF-04', 'Registrar caso con el formulario 1. Los campos opcionales pueden quedar vacíos.', 0),
    (5, 1, 'RF-06', 'Editar caso: admin edita cualquiera; tester solo los que creó.', 0),
    (6, 1, 'RF-20', 'Historial: cada cambio de un caso guarda campo, valor anterior, valor nuevo, usuario y fecha.', 0),
    (7, 1, 'RF-22', 'Consultar resultados: la lista de casos filtra por proyecto, requerimiento y estado.', 0),
    (8, 1, 'RF-05', 'Listar casos: admin ve todos; tester ve los de sus proyectos.', 0),
    (9, 1, 'RF-24', 'Anotar resultado: con OK o FAULT lleva resultado, observaciones y al menos una evidencia. Puede volver a Pendiente.', 0),
    (10, 1, 'RF-02', 'Crear cuenta: registro público con rol tester. Solo un admin crea cuentas admin.', 0),
    (11, 1, 'RF-03', 'Gestionar roles: solo el admin cambia el rol, al editar un usuario.', 0);

INSERT INTO casos_prueba (id, proyecto_id, requerimiento_id, codigo, tipo_prueba, subtecnica, modulo, plataforma,
    entorno, objetivo, precondiciones, entrada, pasos, resultado_esperado, fecha_inicio, fecha_fin,
    estado, resultado_obtenido, observaciones, creado_por, creado_en, anotado_por, anotado_en) VALUES
    (1, 1, 1, 'SIS-001', 3, 1, 'Acceso', 1,
        'Windows 11, Chrome 129, PHP 8.3, MariaDB 11.4',
        'Verificar que un inicio fallido muestra el mismo mensaje si la contraseña es incorrecta o si el usuario no existe.',
        'Existe el usuario gloria. No existe el usuario noexiste.',
        'Clase 1: usuario gloria, contraseña Clave-mala1\nClase 2: usuario noexiste, contraseña Clave-mala1',
        '1. Abrir la página de inicio de sesión.\n2. Entrar con los datos de la clase 1 y anotar el mensaje.\n3. Entrar con los datos de la clase 2 y anotar el mensaje.\n4. Comparar los dos mensajes.',
        'En los dos casos sale "Usuario o contraseña incorrectos." y no se inicia sesión.',
        '2026-10-01', '2026-10-02',
        1, 'Los dos intentos mostraron "Usuario o contraseña incorrectos." y la página siguió en el login.',
        'El usuario escrito se conserva en el campo; la contraseña no.',
        2, '2026-10-01 09:15:00', 2, '2026-10-02 10:40:00'),
    (2, 1, 2, 'SEG-001', 9, 2, 'Evidencias', 1,
        'Ubuntu 24.04, Firefox 131, PHP 8.3, MySQL 8.0',
        'Verificar que solo se aceptan evidencias de hasta 5 MB con extensión permitida.',
        'Sesión iniciada como pan. Existe el caso SIS-001. Archivos preparados: captura-5mb.png (5 242 880 bytes), captura-5mb-mas1.png (5 242 881 bytes) y nota.php.',
        'captura-5mb.png, captura-5mb-mas1.png, nota.php',
        '1. Abrir el caso SIS-001 y anotar estado OK.\n2. Adjuntar captura-5mb.png y guardar.\n3. Repetir con captura-5mb-mas1.png.\n4. Repetir con nota.php.\n5. Revisar storage/evidencias/ y la carpeta public/.',
        'Se acepta el archivo de 5 MB exactos con un nombre nuevo en storage/evidencias/. El de 5 MB y 1 byte y el .php se rechazan con un mensaje junto al campo. Nada se guarda en public/.',
        '2026-10-02', '2026-10-06',
        0, NULL, NULL,
        3, '2026-10-02 14:05:00', NULL, NULL),
    (3, 2, 3, 'INT-001', 2, 3, 'Préstamos', 1,
        'Windows 10, Edge 129, servidor de pruebas de la biblioteca',
        'Verificar las reglas del préstamo con una tabla de decisión: préstamos activos y multa pendiente.',
        'Existen los estudiantes 2024-0101 (0 préstamos, sin multa), 2024-0102 (3 préstamos, sin multa) y 2024-0103 (1 préstamo, multa de RD$50). Hay ejemplares disponibles del libro ISBN 978-84-376-0494-7.',
        'Regla 1: 2024-0101\nRegla 2: 2024-0102\nRegla 3: 2024-0103\nLibro: ISBN 978-84-376-0494-7',
        '1. Entrar como bibliotecario.\n2. Abrir Préstamos > Nuevo.\n3. Buscar al estudiante de la regla 1, elegir el libro y confirmar.\n4. Repetir con las reglas 2 y 3.',
        'Regla 1: se registra el préstamo y baja la existencia. Regla 2: no presta y dice "Tiene 3 préstamos activos". Regla 3: no presta y dice "Tiene una multa sin pagar".',
        '2026-10-03', '2026-10-07',
        0, NULL, NULL,
        2, '2026-10-03 08:30:00', NULL, NULL),
    (4, 1, 5, 'SEG-002', 9, 1, 'Casos', 1,
        'Linux, Firefox, PHP 8.5, MariaDB',
        'Verificar que un tester no edita un caso que creó otra persona, ni desde la pantalla ni enviando el POST a mano.',
        'Pan y Gloria son miembros de Formulación de pruebas. SIS-001 lo creó Gloria. Sesión iniciada como pan.',
        'Caso: SIS-001 (id 1)\nPOST /casos/editar con id=1, el token csrf de la sesión de pan y los campos de SIS-001 con el módulo "Cambiado"',
        '1. Abrir SIS-001 y revisar si sale el botón Editar.\n2. Abrir /casos/editar?id=1.\n3. Enviar el POST de la entrada con curl o las herramientas del navegador.\n4. Entrar como gloria y abrir SIS-001.',
        'No sale el botón Editar. Los pasos 2 y 3 responden 403. SIS-001 no cambia y su historial no tiene filas nuevas.',
        '2026-10-03', '2026-10-05',
        0, NULL, NULL,
        2, '2026-10-03 16:00:00', NULL, NULL),
    (5, 1, 6, 'SIS-002', 3, 1, 'Historial', 1,
        'Linux, Firefox, PHP 8.5, MariaDB',
        'Verificar que cada campo cambiado al editar un caso crea una fila en el historial y que un campo sin cambio no la crea.',
        'Sesión iniciada como gloria. SIS-001 no tiene historial.',
        'Tipo de prueba: Sistema a Regresión\nMódulo: Acceso a Acceso y sesión\nEl resto sin cambio',
        '1. Abrir SIS-001 y pulsar Editar.\n2. Cambiar los dos campos de la entrada y guardar.\n3. Volver a Editar y revisar la tabla Historial.',
        'Salen 2 filas, una por campo, con Gloria y la fecha y hora. El código sigue siendo SIS-001.',
        '2026-10-03', '2026-10-05',
        0, NULL, NULL,
        2, '2026-10-03 16:05:00', NULL, NULL),
    (6, 1, 6, 'INT-001', 2, 12, 'Historial', 1,
        'Linux, Firefox, PHP 8.5, MariaDB',
        'Verificar que si falla el historial, el caso no cambia.',
        'Sesión iniciada como gloria. Acceso a la base con un usuario que puede renombrar tablas.',
        'Módulo de SIS-001: "Prueba de fallo"',
        '1. Abrir SIS-001 y pulsar Editar.\n2. En la base: RENAME TABLE logs_cambios TO logs_cambios_x;\n3. Cambiar el módulo y guardar.\n4. En la base: RENAME TABLE logs_cambios_x TO logs_cambios;\n5. Abrir SIS-001.',
        'El paso 3 muestra el error del servidor. SIS-001 conserva el módulo que tenía.',
        '2026-10-03', '2026-10-05',
        0, NULL, NULL,
        2, '2026-10-03 16:10:00', NULL, NULL),
    (7, 1, 4, 'SIS-003', 3, 2, 'Casos', 1,
        'Linux, Firefox, PHP 8.5, MariaDB',
        'Verificar que un 0 escrito en un campo opcional se guarda como 0 y no como vacío.',
        'Sesión iniciada como gloria.',
        'Entorno: 0\nPrecondiciones: 0',
        '1. Registrar un caso con la entrada y el resto de campos válidos.\n2. Abrir el caso guardado.\n3. Pulsar Editar y revisar los dos campos.',
        'El caso muestra Plataforma "Web · 0" y Precondiciones "0". Al editar, los dos campos tienen 0.',
        '2026-10-03', '2026-10-05',
        0, NULL, NULL,
        2, '2026-10-03 16:15:00', NULL, NULL),
    (8, 1, 6, 'SIS-004', 3, 8, 'Historial', 1,
        'Linux, Firefox, PHP 8.5, MariaDB',
        'Verificar que cualquier miembro del proyecto ve el historial de un caso, aunque no pueda editarlo.',
        'SIS-001 tiene al menos un cambio en el historial (ver SIS-002). Sesión iniciada como pan.',
        'Caso: SIS-001',
        '1. Abrir SIS-001.\n2. Buscar la sección Historial.',
        'Sale la sección Historial con los cambios de SIS-001, y no sale el botón Editar.',
        '2026-10-03', '2026-10-05',
        0, NULL, NULL,
        2, '2026-10-03 16:20:00', NULL, NULL),
    (9, 1, 7, 'SIS-005', 3, 1, 'Casos', 1,
        'Linux, Firefox, PHP 8.5, MariaDB',
        'Verificar que los filtros de la lista de casos se combinan.',
        'Sesión iniciada como admin. Hay casos OK y Pendiente en Formulación de pruebas y casos en Biblioteca escolar.',
        'Proyecto: Formulación de pruebas\nEstado: Pendiente',
        '1. Abrir Casos de prueba.\n2. Elegir el proyecto y el estado de la entrada.\n3. Pulsar Filtrar.',
        'Solo salen casos de Formulación de pruebas en Pendiente. No sale SIS-001 (OK) ni INT-001 de Biblioteca escolar.',
        '2026-10-03', '2026-10-07',
        0, NULL, NULL,
        2, '2026-10-03 17:00:00', NULL, NULL),
    (10, 1, 7, 'SIS-006', 3, 8, 'Casos', 1,
        'Linux, Firefox, PHP 8.5, MariaDB',
        'Verificar que la URL conserva los filtros.',
        'Sesión iniciada como gloria.',
        'Proyecto: Formulación de pruebas\nEstado: OK',
        '1. Filtrar con la entrada.\n2. Copiar la URL y abrirla en otra pestaña.\n3. Recargar la página.',
        'La URL lleva proyecto=1&estado=1. En la otra pestaña y al recargar salen los mismos casos y los selects con lo elegido.',
        '2026-10-03', '2026-10-07',
        0, NULL, NULL,
        2, '2026-10-03 17:05:00', NULL, NULL),
    (11, 1, 7, 'SEG-003', 9, 1, 'Casos', 1,
        'Linux, Firefox, PHP 8.5, MariaDB',
        'Verificar que un tester solo filtra y ve casos de sus proyectos.',
        'Pan solo es miembro de Formulación de pruebas (id 1). Biblioteca escolar es el id 2. Sesión iniciada como pan.',
        'URL: /casos/listar?proyecto=2',
        '1. Abrir Casos de prueba y revisar las opciones de Proyecto y Requerimiento.\n2. Abrir la URL de la entrada.',
        'Proyecto solo ofrece Formulación de pruebas y Requerimiento no muestra los de Biblioteca. La URL muestra "Ningún caso coincide con los filtros"; no sale INT-001 de Biblioteca.',
        '2026-10-03', '2026-10-07',
        0, NULL, NULL,
        3, '2026-10-03 17:10:00', NULL, NULL),
    (12, 1, 7, 'SIS-007', 3, 2, 'Casos', 1,
        'Linux, Firefox, PHP 8.5, MariaDB',
        'Verificar que un estado fuera del catálogo no filtra.',
        'Sesión iniciada como admin. Estados válidos: 0 Pendiente, 1 OK, 2 FAULT.',
        'estado=2\nestado=3\nestado=x',
        '1. Abrir /casos/listar?estado=2.\n2. Abrir /casos/listar?estado=3.\n3. Abrir /casos/listar?estado=x.',
        'Con 2 salen solo los FAULT o el aviso de ningún caso. Con 3 y con x sale la lista completa, sin error, y Estado queda en Todos.',
        '2026-10-03', '2026-10-07',
        0, NULL, NULL,
        2, '2026-10-03 17:15:00', NULL, NULL),
    (13, 1, 7, 'SIS-008', 3, 8, 'Casos', 1,
        'Linux, Firefox, PHP 8.5, MariaDB',
        'Verificar el aviso cuando los filtros no dejan casos.',
        'Sesión iniciada como admin. Ningún caso de Biblioteca escolar está en FAULT.',
        'Proyecto: Biblioteca escolar\nEstado: FAULT',
        '1. Filtrar con la entrada.\n2. Pulsar Limpiar filtros.',
        'Sale "Ningún caso coincide con los filtros" con el formulario de filtros arriba. Limpiar filtros vuelve a /casos/listar con todos los casos.',
        '2026-10-03', '2026-10-07',
        0, NULL, NULL,
        2, '2026-10-03 17:20:00', NULL, NULL),
    (14, 1, 8, 'SIS-009', 3, 1, 'Casos', 1,
        'Linux, Firefox, PHP 8.5, MariaDB',
        'Verificar que admin ve los casos de todos los proyectos y un tester solo los de sus proyectos.',
        'Pan solo es miembro de Formulación de pruebas. Admin no es miembro de ninguno.',
        'Usuarios: admin, pan',
        '1. Entrar como admin y abrir Casos de prueba.\n2. Entrar como pan y abrir Casos de prueba.',
        'Admin ve casos de los dos proyectos, incluido INT-001 de Biblioteca escolar. Pan no ve ningún caso de Biblioteca escolar. En los dos, ordenados por proyecto y código.',
        '2026-10-03', '2026-10-07',
        0, NULL, NULL,
        3, '2026-10-03 17:25:00', NULL, NULL),
    (15, 1, 9, 'SIS-010', 3, 1, 'Casos', 1,
        'Linux, Firefox, PHP 8.5, MariaDB',
        'Verificar que un resultado OK sin evidencia no se guarda.',
        'Sesión iniciada como pan. SIS-002 está Pendiente y sin evidencias.',
        'Estado: OK\nResultado obtenido: Funcionó\nObservaciones: Ninguna\nEvidencias: ninguna marcada',
        '1. Abrir SIS-002.\n2. Anotar la entrada y guardar.',
        'No se guarda. Sale "Con OK o FAULT hace falta al menos una." junto a Evidencias y SIS-002 sigue Pendiente.',
        '2026-10-03', '2026-10-07',
        0, NULL, NULL,
        3, '2026-10-03 17:30:00', NULL, NULL),
    (16, 1, 9, 'SIS-011', 3, 4, 'Casos', 1,
        'Linux, Firefox, PHP 8.5, MariaDB',
        'Verificar que un caso OK puede volver a Pendiente y queda en el historial.',
        'Sesión iniciada como gloria. SIS-001 está OK con una evidencia.',
        'Estado: Pendiente',
        '1. Abrir SIS-001.\n2. Cambiar el estado a Pendiente y guardar.\n3. Pulsar Editar y revisar el historial.',
        'Se guarda sin pedir evidencia nueva. SIS-001 sale Pendiente y el historial tiene una fila de Estado de OK a Pendiente con Gloria.',
        '2026-10-03', '2026-10-07',
        0, NULL, NULL,
        2, '2026-10-03 17:35:00', NULL, NULL),
    (17, 1, 10, 'SIS-012', 3, 2, 'Acceso', 1,
        'Linux, Firefox, PHP 8.5, MariaDB',
        'Verificar el largo mínimo de la contraseña al crear una cuenta.',
        'No existen los usuarios prueba7 ni prueba8.',
        'Clave de 7: Abcdef1\nClave de 8: Abcdef12',
        '1. Abrir Crear cuenta.\n2. Registrar prueba7 con la clave de 7 caracteres.\n3. Registrar prueba8 con la clave de 8 caracteres.',
        'Con 7 no se crea y sale "Mínimo 8 caracteres." junto a la contraseña. Con 8 se crea la cuenta.',
        '2026-10-03', '2026-10-07',
        0, NULL, NULL,
        3, '2026-10-03 18:00:00', NULL, NULL),
    (18, 1, 10, 'SIS-013', 3, 1, 'Acceso', 1,
        'Linux, Firefox, PHP 8.5, MariaDB',
        'Verificar que el registro público crea la cuenta como tester y no repite usuarios.',
        'Existe el usuario gloria. No existe prueba9.',
        'Usuario nuevo: prueba9, clave Abcdef12\nUsuario repetido: gloria, clave Abcdef12',
        '1. Registrar prueba9 y entrar con él.\n2. Revisar si el menú tiene Usuarios y Proyectos.\n3. Volver a Crear cuenta y registrar gloria.',
        'prueba9 entra como tester: el menú no tiene Usuarios ni Proyectos. Con gloria sale "Ese usuario ya existe." y no se crea.',
        '2026-10-03', '2026-10-07',
        0, NULL, NULL,
        3, '2026-10-03 18:05:00', NULL, NULL),
    (19, 1, 11, 'SIS-014', 3, 4, 'Usuarios', 1,
        'Linux, Firefox, PHP 8.5, MariaDB',
        'Verificar que el admin cambia el rol de un tester a admin.',
        'Sesión iniciada como admin. prueba9 es tester (ver SIS-013).',
        'Usuario: prueba9\nRol nuevo: admin',
        '1. Abrir Usuarios y editar prueba9.\n2. Cambiar el rol a admin y guardar.\n3. Salir y entrar como prueba9.\n4. Abrir /admin/usuarios.',
        'La lista muestra prueba9 como admin. Al entrar, prueba9 ve Usuarios y Proyectos en el menú y abre /admin/usuarios.',
        '2026-10-03', '2026-10-07',
        0, NULL, NULL,
        2, '2026-10-03 18:10:00', NULL, NULL),
    (20, 1, 11, 'SIS-015', 3, 1, 'Usuarios', 1,
        'Linux, Firefox, PHP 8.5, MariaDB',
        'Verificar que el admin no se quita su propio rol ni borra su cuenta.',
        'Sesión iniciada como admin.',
        'Usuario: admin\nRol nuevo: tester',
        '1. Abrir Usuarios y editar admin.\n2. Cambiar el rol a tester y guardar.\n3. Volver a Usuarios y buscar el botón Eliminar en la fila de admin.\n4. Enviar POST /admin/usuarios/eliminar con el id de admin y el token csrf.',
        'Paso 2: sale "No puede quitarse su propio rol de admin." y sigue admin. Paso 3: la fila de admin no tiene Eliminar. Paso 4: sale "No puede eliminar su propia cuenta."',
        '2026-10-03', '2026-10-07',
        0, NULL, NULL,
        2, '2026-10-03 18:15:00', NULL, NULL),
    (21, 1, 11, 'SIS-016', 3, 1, 'Usuarios', 1,
        'Linux, Firefox, PHP 8.5, MariaDB',
        'Verificar que no se elimina un usuario con casos a su nombre.',
        'Sesión iniciada como admin. Gloria creó SIS-001.',
        'Usuario: gloria',
        '1. Abrir Usuarios.\n2. Eliminar a gloria y confirmar.',
        'Sale "Tiene casos, evidencias o formularios a su nombre: no se puede eliminar." y gloria sigue en la lista.',
        '2026-10-03', '2026-10-07',
        0, NULL, NULL,
        2, '2026-10-03 18:20:00', NULL, NULL);

-- RF-24: un caso OK lleva al menos una evidencia.
INSERT INTO evidencias (caso_id, tipo, enlace, descripcion, subido_por, subido_en) VALUES
    (1, 4, 'https://github.com/1997-bit/formulacion-pruebas/issues/38', 'Registro de la prueba con las capturas de los dos mensajes.', 2, '2026-10-02 10:40:00');
