<?php

declare(strict_types=1);

// rol: null pública, 0 con sesión, 1 admin.
return [
    'GET /' => ['controlador' => 'Acceso', 'accion' => 'login', 'rol' => null, 'rf' => 'RF-01'],
    'POST /' => ['controlador' => 'Acceso', 'accion' => 'entrar', 'rol' => null, 'rf' => 'RF-01'],
    'GET /registro' => ['controlador' => 'Acceso', 'accion' => 'registro', 'rol' => null, 'rf' => 'RF-02'],
    'POST /registro' => ['controlador' => 'Acceso', 'accion' => 'registrar', 'rol' => null, 'rf' => 'RF-02'],
    'GET /salir' => ['controlador' => 'Acceso', 'accion' => 'salir', 'rol' => 0, 'rf' => 'RF-01'],
    'GET /dashboard' => ['controlador' => 'Panel', 'accion' => 'ver', 'rol' => 0, 'rf' => 'RF-23'],
    'GET /requerimientos/listar' => ['controlador' => 'Requerimientos', 'accion' => 'listar', 'rol' => 0, 'rf' => 'RF-04'],
    'GET /requerimientos/registrar' => ['controlador' => 'Requerimientos', 'accion' => 'registrar', 'rol' => 0, 'rf' => 'RF-04'],
    'POST /requerimientos/registrar' => ['controlador' => 'Requerimientos', 'accion' => 'guardar', 'rol' => 0, 'rf' => 'RF-04'],
    'GET /casos/listar' => ['controlador' => 'Casos', 'accion' => 'listar', 'rol' => 0, 'rf' => 'RF-05'],
    'GET /casos/registrar' => ['controlador' => 'Casos', 'accion' => 'registrar', 'rol' => 0, 'rf' => 'RF-04'],
    'POST /casos/registrar' => ['controlador' => 'Casos', 'accion' => 'guardar', 'rol' => 0, 'rf' => 'RF-04'],
    'GET /casos/resultado' => ['controlador' => 'Casos', 'accion' => 'resultado', 'rol' => 0, 'rf' => 'RF-24'],
    'POST /casos/resultado' => ['controlador' => 'Casos', 'accion' => 'anotar', 'rol' => 0, 'rf' => 'RF-24'],
    'GET /evidencias/ver' => ['controlador' => 'Evidencias', 'accion' => 'ver', 'rol' => 0, 'rf' => 'RF-24'],
    'GET /casos/editar' => ['controlador' => 'Casos', 'accion' => 'editar', 'rol' => 0, 'rf' => 'RF-06'],
    'POST /casos/editar' => ['controlador' => 'Casos', 'accion' => 'actualizar', 'rol' => 0, 'rf' => 'RF-06'],
    'POST /casos/eliminar' => ['controlador' => 'Casos', 'accion' => 'eliminar', 'rol' => 1, 'rf' => 'RF-07'],
    'GET /formularios/portafolio' => ['controlador' => 'Evidencias', 'accion' => 'portafolio', 'rol' => 0, 'rf' => 'RF-16'],
    'GET /formularios/incidentes' => ['controlador' => 'Incidentes', 'accion' => 'listar', 'rol' => 0, 'rf' => 'RF-19'],
    'GET /formularios/incidentes/registrar' => ['controlador' => 'Incidentes', 'accion' => 'registrar', 'rol' => 0, 'rf' => 'RF-17'],
    'POST /formularios/incidentes/registrar' => ['controlador' => 'Incidentes', 'accion' => 'guardar', 'rol' => 0, 'rf' => 'RF-17'],
    'GET /formularios/incidentes/ver' => ['controlador' => 'Incidentes', 'accion' => 'ver', 'rol' => 0, 'rf' => 'RF-19'],
    'POST /formularios/incidentes/ver' => ['controlador' => 'Incidentes', 'accion' => 'actualizar', 'rol' => 0, 'rf' => 'RF-19'],
    'GET /admin/usuarios' => ['controlador' => 'Usuarios', 'accion' => 'listar', 'rol' => 1, 'rf' => 'RF-03'],
    'GET /admin/usuarios/crear' => ['controlador' => 'Usuarios', 'accion' => 'crear', 'rol' => 1, 'rf' => 'RF-02'],
    'POST /admin/usuarios/crear' => ['controlador' => 'Usuarios', 'accion' => 'guardar', 'rol' => 1, 'rf' => 'RF-02'],
    'GET /admin/usuarios/editar' => ['controlador' => 'Usuarios', 'accion' => 'editar', 'rol' => 1, 'rf' => 'RF-03'],
    'POST /admin/usuarios/editar' => ['controlador' => 'Usuarios', 'accion' => 'actualizar', 'rol' => 1, 'rf' => 'RF-03'],
    'POST /admin/usuarios/eliminar' => ['controlador' => 'Usuarios', 'accion' => 'eliminar', 'rol' => 1, 'rf' => 'RF-03'],
    'GET /admin/proyectos' => ['controlador' => 'Proyectos', 'accion' => 'listar', 'rol' => 1, 'rf' => 'RF-21'],
    'GET /admin/proyectos/crear' => ['controlador' => 'Proyectos', 'accion' => 'crear', 'rol' => 1, 'rf' => 'RF-21'],
    'POST /admin/proyectos/crear' => ['controlador' => 'Proyectos', 'accion' => 'guardar', 'rol' => 1, 'rf' => 'RF-21'],
    'GET /admin/proyectos/editar' => ['controlador' => 'Proyectos', 'accion' => 'editar', 'rol' => 1, 'rf' => 'RF-21'],
    'POST /admin/proyectos/editar' => ['controlador' => 'Proyectos', 'accion' => 'actualizar', 'rol' => 1, 'rf' => 'RF-21'],
    'POST /admin/proyectos/eliminar' => ['controlador' => 'Proyectos', 'accion' => 'eliminar', 'rol' => 1, 'rf' => 'RF-21'],
];
